export * from './HomePage';
export * from './CellPhones';
export * from './AboutPage';
export * from './CellPhonePage';
export * from './Loginpage';
export * from './Registro';
export * from './OrdersUserPage';
export * from './CheckoutPage';
export * from './ThankyouPage';